builders:
  generateRepository:
    import: "package:clean_annotation_generator/builder.dart"
    builder_factories: ["generateRepository"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  generateSample:
    import: "package:clean_annotation_generator/builder.dart"
    builder_factories: ["generateSample"]
    build_extensions: { ".dart": [".sample.part"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["clean_annotation_generator|generateRepository"]
    applies_builders: ["source_gen|combining_builder"]
