name: clean_annotation_generator
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # annotation package
  clean_annotation:
    path: ../clean_annotation/
  
  # source_gen
  source_gen: ^1.2.7
  
  # build
  build: ^2.3.1

  cupertino_icons: ^1.0.2
  glob: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #build_runner
  build_runner: ^2.3.3

  #build_test
  build_test: ^2.1.7
  
 
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
